### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by chriscz** [absortium/poloniex-api#15]
Hi guys thanks for this project.

I would like to know what license before making any significant contributions to the project. I recommend these, in order of my preference:
- [MPL](https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)), 
- [BSD](https://tldrlegal.com/license/bsd-3-clause-license-(revised)), 
- [Apache](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) or 
- [LGPL](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)).

**Comment by AndrewSamokhvalov** [comment]
Hi @chriscz! Thanks for bringing this up, could you create a pull request and choose any of the licence above? I would be really appreciate.

**Comment by chriscz** [comment]
Cool, I'll do it this weekend. I'm gonna go with BSD on this. The BSD license doesn't require that changes be open-sourced whereas MPL does. Let me know if that's ok.

**Comment by AndrewSamokhvalov** [comment]
@chriscz That is totally okay for me 👍

**Comment by AndrewSamokhvalov** [comment]
@chriscz But actually, maybe we could do `MIT` instead?

**Comment by chriscz** [comment]
Sure thing!
