### ISSUE TITLE
"Nonce must be greater than XXX. You provided YYY."

### ISSUE THREAD

**Issue by Sajam** [absortium/poloniex-api#19]
It happens sometimes:

```
Traceback (most recent call last):
  [...]
  File "/src/poloniex/poloniex/api/base.py", line 51, in decorator
    return self.response_handler(response, command=func.__name__)
  File "/src/poloniex/poloniex/api/base.py", line 291, in response_handler
    raise PoloniexError(response["error"])
poloniex.error.PoloniexError: Nonce must be greater than 1501656476332. You provided 1501656476302.
```

So, the value provided is Monday, 08-Aug-55 06:58:22 UTC and expected must be greater than Monday, 08-Aug-55 06:58:52 UTC (30 seconds difference). Maybe it's caused by long waiting time? Maybe it can be solved by setting greater nonce?

**Comment by Sajam** [comment]
This is a multiprocessing issue, sorry.

**Comment by JBaczuk** [comment]
@Sajam Can you comment further on this issue, I'm having a similar issue.
